services:
  - type: web
    name: gym-management
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gym-management-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: gym-management-db
    plan: free
